import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import servicesRouter from "./services";
import productsRouter from "./products";
import coursesRouter from "./courses";
import galleryRouter from "./gallery";
import reviewsRouter from "./reviews";
import bookingsRouter from "./bookings";
import cartRouter from "./cart";
import wishlistRouter from "./wishlist";
import ordersRouter from "./orders";
import paymentsRouter from "./payments";
import adminOrdersRouter from "./adminOrders";
import adminUsersRouter from "./adminUsers";
import adminStatsRouter from "./adminStats";
import siteSettingsRouter from "./siteSettings";
import articlesRouter from "./articles";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(servicesRouter);
router.use(productsRouter);
router.use(coursesRouter);
router.use(galleryRouter);
router.use(reviewsRouter);
router.use(bookingsRouter);
router.use(cartRouter);
router.use(wishlistRouter);
router.use(ordersRouter);
router.use(paymentsRouter);
router.use(adminOrdersRouter);
router.use(adminUsersRouter);
router.use(adminStatsRouter);
router.use(siteSettingsRouter);
router.use(articlesRouter);

export default router;
